name: 'Installs Bearer CLI'
description: 'Installs Bearer CLI'

# inputs:
#   npm-token:
#     description: 'NPM token for package installation'
#     required: true

runs:
  using: "composite"
  steps:
    - name: Install
      shell: bash
      run: |
        sudo apt-get install apt-transport-https
        echo "deb [trusted=yes] https://apt.fury.io/bearer/ /" | sudo tee -a /etc/apt/sources.list.d/fury.list
        sudo apt-get update
        sudo apt-get install bearer
      # env:
      #   NPM_CONFIG_IGNORE_SCRIPTS: true
