name: Vulnerability Scan

on: push

jobs:
  yarn-test-integration:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Test
        id: test
        run: pwd
