name: Vulnerability Scan

on: push

jobs:
  vulnerability-scan:
    name: vulnerability-scan
    timeout-minutes: 5
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4

      # - name: Setup Bearer
      #   uses: ./.github/actions/install_bearer

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::621890795306:role/Github-S3
          role-session-name: gitHubActions

      # - name: Scan
      #   id: test
      #   run: |
      #     bearer scan ./demoapp --fail-on-severity critical
      - name: Check AWS Session
        run: |
          # Your commands that require AWS credentials
          aws sts get-caller-identity

      - name: Test S3 connection
        run: |
          # Your commands that require AWS credentials
          echo "tester\n" > /tmp/testfile && aws s3api put-object --bucket opentext-demo-code-audit --key vuln-scans/test.txt --body /tmp/testfile
