name: Vulnerability Scan

on: push

jobs:
  vulnerability-scan:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bearer
        uses: ./.github/actions/install_bearer

      - name: Scan
        id: test
        run: |
          bearer scan ./demoapp
